# fly.toml app configuration file generated for honobackend on 2024-08-04T09:13:21+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'honobackend'
primary_region = 'sin'  # Singapore is cost-effective, alternatives: 'bom' (Mumbai), 'hkg' (Hong Kong)

[build]
  image = "cecep31/honobackend:latest"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = "stop"  # Automatically stop machines when idle
  auto_start_machines = true  # Automatically start machines when needed
  min_machines_running = 0    # Saves cost by scaling to 0 when not in use
  min_idle_count = 0          # Number of machines to keep running when idle (0 = stop all when idle)
  processes = ['app']
  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '256mb'    # Minimum memory configuration
  cpu_kind = 'shared'  # Shared CPUs are more cost-effective
  cpus = 1            # Single CPU core
  memory_mb = 256     # Explicit memory limit in MB
  swap_size_mb = 128  # Add swap to help with memory spikes
