name: build

on:
  push:
    branches:
      - 'main'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: install depedency
        run: bun install

      - name: build
        run: bun run build

